In [1]:
import numpy as np

## Numpy

### Массивы

Генерация массива в numpy:

In [2]:
a = np.arange(5, 10, 2)
print(a, type(a))

[5 7 9] <class 'numpy.ndarray'>


In [3]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

Можно привести список к numpy массиву:

In [4]:
x = np.array([1, 2, 3], dtype=float)
print(x, type(x))

[1. 2. 3.] <class 'numpy.ndarray'>


Двумерные (и не только) массивы:

In [5]:
xx = np.array([[1, 1, 1], [2, 3, 4]])
print(xx)
print("Кол-во измерений:", xx.ndim)
print("Кол-во строк и столбцов", xx.shape)
print(xx[0])
print(xx[1][0])
print(xx[1, 0])

[[1 1 1]
 [2 3 4]]
Кол-во измерений: 2
Кол-во строк и столбцов (2, 3)
[1 1 1]
2
2


### Операции с векторами и матрицами

In [6]:
arr = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print("исходный массив:\n", arr, sep="\n")
print("-"*9)
print("arr * arr:\n", arr*arr, sep="\n") # поэлементное умножение
print("-"*9)
print("arr @ arr:\n", arr@arr, sep="\n") # матричное умножение
print("-"*9)
print("arr.dot(arr):\n", arr.dot(arr), sep="\n") # матричное умножение
print("-"*9)
print("arr + arr:\n", arr+arr, sep="\n") # сложение
print("-"*9)
print("arr - arr:\n", arr-arr, sep="\n") # вычитание
print("-"*9)
print("arr / arr:\n", arr/arr, sep="\n") # деление
print("-"*9)

исходный массив:

[[1 1 1]
 [2 2 2]
 [3 3 3]]
---------
arr * arr:

[[1 1 1]
 [4 4 4]
 [9 9 9]]
---------
arr @ arr:

[[ 6  6  6]
 [12 12 12]
 [18 18 18]]
---------
arr.dot(arr):

[[ 6  6  6]
 [12 12 12]
 [18 18 18]]
---------
arr + arr:

[[2 2 2]
 [4 4 4]
 [6 6 6]]
---------
arr - arr:

[[0 0 0]
 [0 0 0]
 [0 0 0]]
---------
arr / arr:

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
---------


In [7]:
print("arr.T:\n", arr.T, sep="\n") # транспонирование

arr.T:

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Генерация случайных значений

генерация случайных значений из равномерного
распределения от 0 до 1

In [8]:
np.random.rand()

0.14129351824077252

In [9]:
np.random.rand(3, 2)

array([[0.56476828, 0.57201094],
       [0.63830347, 0.97972268],
       [0.07761528, 0.47675228]])

In [10]:
min_v = 2
max_v = 5

min_v + (max_v - min_v) * np.random.rand(3, 2) 

array([[2.15942399, 4.40481725],
       [4.16189634, 2.09494631],
       [2.02669734, 3.4053231 ]])